@startuml

actor "User" as user
rectangle "System" {
  rectangle "Component A" as componentA
  rectangle "Component B" as componentB
}

user -> componentA : Request
componentA --> componentB : Process
user <- componentB : Response

@enduml
